name: docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker buildx
        uses: docker/setup-buildx-action@v1

      - name: docker build
        uses: docker/build-push-action@v2
        with:
          context: /home/runner/work/aiof-asset/aiof-asset/app/publish/
          push: false
          tags: gkama/aiof-asset:latest

