name: docker

env:
  configuration: release
  project_file: aiof.asset.core/aiof.asset.core.csproj
  project_test_file: aiof.asset.tests/aiof.asset.tests.csproj
  outputPath: app/publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: docker buildx
      uses: docker/setup-buildx-action@v1

    - name: bash ls
      run: ls ${{ env.outputPath }}

    - name: docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: gkama/aiof-asset:latest
    
    - name: docker login
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
