name: release

env:
  configuration: release
  project_file: aiof.asset.core/aiof.asset.core.csproj
  project_test_file: aiof.asset.tests/aiof.asset.tests.csproj
  output_path: app/publish

on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        required: true
        default: dev

jobs:
  release:
    environment: ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: env
      run: |
        echo "running environment ${{ github.event.inputs.env }}"

    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: restore
      run: dotnet restore ${{ env.project_file }}
      
    - name: build
      run: dotnet build -c ${{ env.configuration }} ${{env.project_file }} --no-restore

    - name: test
      run: dotnet test -c ${{ env.configuration }} ${{ env.project_test_file }} -l trx -v normal --no-build

    - name: publish
      run: dotnet publish -c ${{ env.configuration }} -o ${{ env.output_path }}

    - name: docker buildx
      uses: docker/setup-buildx-action@v1

    - name: docker login
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gkama/aiof-asset:latest

    - name: az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: az webapp restart
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az webapp restart -n ${{ secrets.AZURE_APP_NAME }} -g ${{ secrets.AZURE_APP_RESOURCE_GROUP }}
